const birthmonth=document.querySelector('#month').value
const birthday=document.querySelector('#day').value
const aquarius=document.querySelector('#aquarius')
const aries=document.querySelector('#aries')
const cancer=document.querySelector('#cancer')
const capricorn=document.querySelector('#capricorn')
const gemini=document.querySelector('#gemini')
const leo=document.querySelector('#leo')
const libra=document.querySelector('#libra')
const pisces=document.querySelector('#pisces')
const sagittarius=document.querySelector('#sagittarius')
const scorpio=document.querySelector('#scorpio')
const taurus=document.querySelector('#taurus')
const virgo=document.querySelector('#virgo')

document.querySelector('button').addEventListener('click', zodiac)

function zodiac(){
    const birthmonth=document.querySelector('#month').value
    const birthday=document.querySelector('#day').value
    if(birthmonth==1 && birthday >= 20|| birthmonth== 2 && birthday<=18){
        aquarius.classList.toggle('hidden')
	    aries.classList.add('hidden')
        cancer.classList.add('hidden')
        capricorn.classList.add('hidden')
        leo.classList.add('hidden')
        libra.classList.add('hidden')
        pisces.classList.add('hidden')
        sagittarius.classList.add('hidden')
        scorpio.classList.add('hidden')
        taurus.classList.add('hidden')
        virgo.classList.add('hidden')
        gemini.classList.add('hidden')
    }else if(birthmonth== 2&& birthday >= 19 || birthmonth ==3&& birthday <= 20){
        aquarius.classList.add('hidden')
	    aries.classList.add('hidden')
        cancer.classList.add('hidden')
        capricorn.classList.add('hidden')
        leo.classList.add('hidden')
        libra.classList.add('hidden')
        pisces.classList.toggle('hidden')
        sagittarius.classList.add('hidden')
        scorpio.classList.add('hidden')
        taurus.classList.add('hidden')
        virgo.classList.add('hidden')
        gemini.classList.add('hidden')
    }else if(birthmonth== 3&& birthday >= 21 || birthmonth ==4&& birthday <= 19){
        aquarius.classList.add('hidden')
	    aries.classList.toggle('hidden')
        cancer.classList.add('hidden')
        capricorn.classList.add('hidden')
        leo.classList.add('hidden')
        libra.classList.add('hidden')
        pisces.classList.add('hidden')
        sagittarius.classList.add('hidden')
        scorpio.classList.add('hidden')
        taurus.classList.add('hidden')
        virgo.classList.add('hidden')
        gemini.classList.add('hidden')
    }else if(birthmonth== 4&& birthday >= 20 || birthmonth ==5&& birthday <= 20){
        aquarius.classList.add('hidden')
	    aries.classList.add('hidden')
        cancer.classList.add('hidden')
        capricorn.classList.add('hidden')
        leo.classList.add('hidden')
        libra.classList.add('hidden')
        pisces.classList.add('hidden')
        sagittarius.classList.add('hidden')
        scorpio.classList.add('hidden')
        taurus.classList.toggle('hidden')
        virgo.classList.add('hidden')
        gemini.classList.add('hidden')
    }else if(birthmonth== 5&& birthday >= 21 || birthmonth ==6&& birthday <= 20){
        aquarius.classList.add('hidden')
	    aries.classList.add('hidden')
        cancer.classList.add('hidden')
        capricorn.classList.add('hidden')
        leo.classList.add('hidden')
        libra.classList.add('hidden')
        pisces.classList.add('hidden')
        sagittarius.classList.add('hidden')
        scorpio.classList.add('hidden')
        taurus.classList.add('hidden')
        virgo.classList.add('hidden')   
        gemini.classList.toggle('hidden')
    }else if(birthmonth== 5&& birthday >= 21 || birthmonth ==6&& birthday <= 20){
        aquarius.classList.add('hidden')
	    aries.classList.add('hidden')
        cancer.classList.add('hidden')
        capricorn.classList.add('hidden')
        leo.classList.add('hidden')
        libra.classList.add('hidden')
        pisces.classList.add('hidden')
        sagittarius.classList.add('hidden')
        scorpio.classList.add('hidden')
        taurus.classList.add('hidden')
        virgo.classList.add('hidden')   
        gemini.classList.toggle('hidden') 
    }else if(birthmonth== 6&& birthday >= 21 || birthmonth ==7&& birthday <= 22){
        aquarius.classList.add('hidden')
	    aries.classList.add('hidden')
        cancer.classList.toggle('hidden')
        capricorn.classList.add('hidden')
        leo.classList.add('hidden')
        libra.classList.add('hidden')
        pisces.classList.add('hidden')
        sagittarius.classList.add('hidden')
        scorpio.classList.add('hidden')
        taurus.classList.add('hidden')
        virgo.classList.add('hidden')   
        gemini.classList.add('hidden') 
    }else if(birthmonth== 7&& birthday >= 23 || birthmonth ==8&& birthday <= 22){
        aquarius.classList.add('hidden')
	    aries.classList.add('hidden')
        cancer.classList.add('hidden')
        capricorn.classList.add('hidden')
        leo.classList.toggle('hidden')
        libra.classList.add('hidden')
        pisces.classList.add('hidden')
        sagittarius.classList.add('hidden')
        scorpio.classList.add('hidden')
        taurus.classList.add('hidden')
        virgo.classList.add('hidden')   
        gemini.classList.add('hidden') 
    }else if(birthmonth== 8&& birthday >= 23 || birthmonth ==9&& birthday <= 22){
        aquarius.classList.add('hidden')
	    aries.classList.add('hidden')
        cancer.classList.add('hidden')
        capricorn.classList.add('hidden')
        leo.classList.add('hidden')
        libra.classList.add('hidden')
        pisces.classList.add('hidden')
        sagittarius.classList.add('hidden')
        scorpio.classList.add('hidden')
        taurus.classList.add('hidden')
        virgo.classList.toggle('hidden')   
        gemini.classList.add('hidden')   
    }else if(birthmonth== 9&& birthday >= 23 || birthmonth ==10&& birthday <= 22){
        aquarius.classList.add('hidden')
	    aries.classList.add('hidden')
        cancer.classList.add('hidden')
        capricorn.classList.add('hidden')
        leo.classList.add('hidden')
        libra.classList.toggle('hidden')
        pisces.classList.add('hidden')
        sagittarius.classList.add('hidden')
        scorpio.classList.add('hidden')
        taurus.classList.add('hidden')
        virgo.classList.add('hidden')   
        gemini.classList.add('hidden')    
    }else if(birthmonth== 10&& birthday >= 23 || birthmonth ==11&& birthday <= 21){
        aquarius.classList.add('hidden')
	    aries.classList.add('hidden')
        cancer.classList.add('hidden')
        capricorn.classList.add('hidden')
        leo.classList.add('hidden')
        libra.classList.add('hidden')
        pisces.classList.add('hidden')
        sagittarius.classList.add('hidden')
        scorpio.classList.toggle('hidden')
        taurus.classList.add('hidden')
        virgo.classList.add('hidden')   
        gemini.classList.add('hidden')  
    }else if(birthmonth== 11&& birthday >= 22 || birthmonth ==12&& birthday <= 21){
        aquarius.classList.add('hidden')
	    aries.classList.add('hidden')
        cancer.classList.add('hidden')
        capricorn.classList.add('hidden')
        leo.classList.add('hidden')
        libra.classList.add('hidden')
        pisces.classList.add('hidden')
        sagittarius.classList.toggle('hidden')
        scorpio.classList.add('hidden')
        taurus.classList.add('hidden')
        virgo.classList.add('hidden')   
        gemini.classList.add('hidden') 
    }else if(birthmonth== 12&& birthday >= 22 || birthmonth ==1&& birthday <= 19){
        aquarius.classList.add('hidden')
	    aries.classList.add('hidden')
        cancer.classList.add('hidden')
        capricorn.classList.toggle('hidden')
        leo.classList.add('hidden')
        libra.classList.add('hidden')
        pisces.classList.add('hidden')
        sagittarius.classList.add('hidden')
        scorpio.classList.add('hidden')
        taurus.classList.add('hidden')
        virgo.classList.add('hidden')   
        gemini.classList.add('hidden') 
}
}

